# This file is machine-generated - editing it directly is not advised

[[ATK_jll]]
deps = ["Glib_jll", "Libdl", "Pkg"]
git-tree-sha1 = "7129d58ed99d42032cefe21bcd14171a878143d2"
uuid = "7b86fcea-f67b-53e1-809c-8f1719c154e8"
version = "2.34.1+2"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Bzip2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "3663bfffede2ef41358b6fc2e1d8a6d50b3c3904"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.6+2"

[[Cairo]]
deps = ["Cairo_jll", "Colors", "Fontconfig_jll", "Glib_jll", "Graphics", "Libdl", "Pango_jll"]
git-tree-sha1 = "639345ddd8d7f52bbca32a847d74a5a497c4e4bc"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "1.0.2"

[[Cairo_jll]]
deps = ["Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "X11_jll", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "e7bd31d1588b711113d48c7013a7d8f0b5203940"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.0+3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "b9de8dc6106e09c79f3f776c27c62360d30e5eb8"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.9.1"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport"]
git-tree-sha1 = "177d8b959d3c103a6d57574c38ee79c81059c31b"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.11.2"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Dbus_jll]]
deps = ["Expat_jll", "Libdl", "Pkg"]
git-tree-sha1 = "72ff4d947383cc009e02d322f14c7653f7ab4b21"
uuid = "ee1fde0b-3d02-5ea6-8484-8dfef6360eab"
version = "1.12.16+0"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Expat_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9cdd4b1523086c9d93604599e3a389e8941e52b0"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.7+1"

[[FixedPointNumbers]]
git-tree-sha1 = "4aaea64dd0c30ad79037084f8ca2b94348e65eaa"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.7.1"

[[Fontconfig_jll]]
deps = ["Bzip2_jll", "Expat_jll", "FreeType2_jll", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "141fe5f6d4013304d2ca5af0ac20ef4855bcc4e5"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.1+11"

[[FreeType2_jll]]
deps = ["Bzip2_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "7d900f32a3788d4eacac2bfa3bf5c770179c8afd"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.1+2"

[[FriBidi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e479537bf8a8f060c546553c14fd0633978dda7e"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.5+2"

[[GTK3_jll]]
deps = ["ATK_jll", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "Graphene_jll", "HarfBuzz_jll", "Libdl", "Libepoxy_jll", "Pango_jll", "Pkg", "Wayland_jll", "Xorg_libX11_jll", "Xorg_libXcomposite_jll", "Xorg_libXcursor_jll", "Xorg_libXdamage_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll", "Xorg_libXrender_jll", "adwaita_icon_theme_jll", "at_spi2_atk_jll", "gdk_pixbuf_jll", "iso_codes_jll", "xkbcommon_jll"]
git-tree-sha1 = "19f11cf4e1b25ed45adb1c26c9877ebc212aca99"
uuid = "77ec8976-b24b-556a-a1bf-49a033a670a6"
version = "3.24.11+1"

[[Gettext_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "e43d686df1f45cab7a2570ff63642a3ea618ca5f"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+2"

[[Glib_jll]]
deps = ["Gettext_jll", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "09ea3797c586eedbb383eb8f1c950a12923f1541"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.59.0+2"

[[Graphene_jll]]
deps = ["Glib_jll", "Libdl", "Pkg"]
git-tree-sha1 = "9d0b534de52582b7f1f044d622b858915dc6b126"
uuid = "75302f13-0b7e-5bab-a6d1-23fa92e4c2ea"
version = "1.10.0+2"

[[Graphics]]
deps = ["Colors", "LinearAlgebra", "NaNMath"]
git-tree-sha1 = "45d684ead5b65c043ad46bd5be750d61c39d7ef8"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.0.2"

[[Graphite2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "6fad1258f2c9eacb86e8726d38c2ad6549f9d91e"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.13+1"

[[Gtk]]
deps = ["Cairo", "Cairo_jll", "Dates", "GTK3_jll", "Glib_jll", "Graphics", "Libdl", "Pkg", "Reexport", "Serialization", "Test", "Xorg_xkeyboard_config_jll", "adwaita_icon_theme_jll", "gdk_pixbuf_jll", "hicolor_icon_theme_jll"]
git-tree-sha1 = "375b6b23cea83030e68273a696e8a5a7bb90953a"
uuid = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
version = "1.1.3"

[[HarfBuzz_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Gettext_jll", "Glib_jll", "Graphite2_jll", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "dbc6a8c98abe861dd928bc2b603b4ee1eed41dcd"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.6.1+4"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JpegTurbo_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b007cedc10bb017cdae3af0062fe4dd29b483c70"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.0.1+0"

[[LZO_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "71119990371c93f027bee80547ee908ddfe7c5ca"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+1"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libepoxy_jll]]
deps = ["Libdl", "Libglvnd_jll", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "2edab6849416951df6866b939c149b07bb001f37"
uuid = "42c93a91-0102-5b3f-8f9d-e41de60ac950"
version = "1.5.4+0"

[[Libffi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "68b165c609961207baa3174e03d6d56e7a37124c"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.1+1"

[[Libgcrypt_jll]]
deps = ["Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "7efb7f5e75a0f7323cce366d3e44a2d225c5617a"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.5+1"

[[Libglvnd_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "30a990af9ce535bcba54d1f23f071a7e714f861e"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+1"

[[Libgpg_error_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "334284a62d6b8592099d28b78c76aefc266c03a2"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.36.0+1"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e5256a3b0ebc710dbd6da0c0b212164a3681037f"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+2"

[[Libmount_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "621a6d7d527fd8e4812ca1154567bfdb81a3c517"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.34.0+1"

[[Libtiff_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "6cab365abd0108b45e1cbd234223152d88647742"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.0.10+0"

[[Libuuid_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7ae7eee3a9fe811b656347700c17fc9620ef4ecf"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.34.0+4"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[NaNMath]]
git-tree-sha1 = "928b8ca9b2791081dc71a51c55347c27c618760f"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.3"

[[PCRE_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2c860a32ae9c421b52b654448bd31a31f437449a"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.42.0+2"

[[Pango_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "Libdl", "Pkg"]
git-tree-sha1 = "99ee35d5298b2615c800becfea2b3dc4fdb803c5"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.42.4+7"

[[Pixman_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ae66367153a89ecb2a5c7acc2df4ba082b729b6a"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.38.4+2"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[Wayland_jll]]
deps = ["Expat_jll", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "77e7b942a796bc9530f089099e3caeef6cc123f9"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.17.0+1"

[[Wayland_protocols_jll]]
deps = ["Libdl", "Pkg", "Wayland_jll"]
git-tree-sha1 = "d53533e9cbc71f1274b20f4af76c4f13e6e4a8a0"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.18.0+1"

[[X11_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "dfadaea7e3fa9120b06824b634342fc6cba58109"
uuid = "546b0b6d-9ca3-5ba2-8705-1bc1841d8479"
version = "1.6.8+5"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "39a309feb51413d39bdf544cf2fd09357bae37d2"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.9+2"

[[XSLT_jll]]
deps = ["Libdl", "Libgcrypt_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "d0baa21427b6621126bd9e9941b4f51bef5f9fca"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.33+1"

[[Xorg_compositeproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "264e520f4c754e87e2609519cb994fe4c0999acd"
uuid = "0af4abc2-9bda-511f-85a5-daebf69421ba"
version = "0.4.0+0"

[[Xorg_damageproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "eadb7238c6bf4abf8ba6644a132bcfbe9d051e2a"
uuid = "17eb5352-d50b-5fdc-b767-c749cd790e65"
version = "1.2.1+0"

[[Xorg_fixesproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "101dcd548d6021b8d3cdaeb66c65c0d85faf1bcb"
uuid = "cf2f014d-5496-555f-b295-889ac9dfddaa"
version = "5.0.0+0"

[[Xorg_inputproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "6f05096d08266571e6214fd2525f3e78b2c63060"
uuid = "84d6cd60-beca-5f49-93c5-789031781a2d"
version = "2.3.2+1"

[[Xorg_libX11_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "b04e87c6b8a7f80aa9f8239dd5d23bb3324728fa"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+1"

[[Xorg_libXau_jll]]
deps = ["Libdl", "Pkg", "Xorg_xproto_jll"]
git-tree-sha1 = "711f2bbdbb0e90b90a71c5ccf835137e2def539a"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+2"

[[Xorg_libXcomposite_jll]]
deps = ["Libdl", "Pkg", "Xorg_compositeproto_jll", "Xorg_libXfixes_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "833b65aac6c40d0df974feb407c30b6cb123ee55"
uuid = "3c9796d7-64a0-5134-86ad-79f8eb684845"
version = "0.4.5+1"

[[Xorg_libXcursor_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "2a5883ed563bd0da8976449ea31bba8a922a13c4"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+1"

[[Xorg_libXdamage_jll]]
deps = ["Libdl", "Pkg", "Xorg_damageproto_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "40f27a2edeb664f92165addec7d72be56d57ca5b"
uuid = "0aeada51-83db-5f97-b67e-184615cfc6f6"
version = "1.1.5+1"

[[Xorg_libXdmcp_jll]]
deps = ["Libdl", "Pkg", "Xorg_util_macros_jll", "Xorg_xproto_jll"]
git-tree-sha1 = "1ffd7bc9c9d8bba6652516f3402ee1ef5f4cac70"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+2"

[[Xorg_libXext_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_util_macros_jll", "Xorg_xextproto_jll"]
git-tree-sha1 = "43ff58a4d17cc9710bfadccaa7249f2e44c4b20b"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+1"

[[Xorg_libXfixes_jll]]
deps = ["Libdl", "Pkg", "Xorg_fixesproto_jll", "Xorg_libX11_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "ff358baf2b575c149d2115a6a1a2ca772868ee97"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+1"

[[Xorg_libXi_jll]]
deps = ["Libdl", "Pkg", "Xorg_inputproto_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "4ea59b9d391a81553d24d68b15dd191e8fe39afc"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+1"

[[Xorg_libXinerama_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_util_macros_jll", "Xorg_xineramaproto_jll"]
git-tree-sha1 = "fd650df461ecdd390f40d5d909e59e725d44f44c"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+1"

[[Xorg_libXrandr_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Xorg_randrproto_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "eda897668a2a6757a75a46c866b753ad6840a75c"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+1"

[[Xorg_libXrender_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_renderproto_jll"]
git-tree-sha1 = "84708092aaae22c33c120064a36f1853a2d99d94"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+1"

[[Xorg_libXtst_jll]]
deps = ["Libdl", "Pkg", "Xorg_inputproto_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_libXi_jll", "Xorg_recordproto_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "81a154ce423d2346d80b5a700acbfb9f60dfd733"
uuid = "b6f176f1-7aea-5357-ad67-1d3e565ea1c6"
version = "1.2.3+1"

[[Xorg_libpthread_stubs_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ec1e2973e4e624069be95f806dbd7e225fee26c6"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+1"

[[Xorg_libxcb_jll]]
deps = ["Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll", "Xorg_util_macros_jll", "Xorg_xcb_proto_jll"]
git-tree-sha1 = "6f5c3e3d1e3201613f38c4042ca79521e3c0bb97"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+1"

[[Xorg_libxkbfile_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "b9c6a72a1e4bcb10d8d50bb8482fdbd1ad447b21"
uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a"
version = "1.1.0+1"

[[Xorg_randrproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "5c2f995614980bedaed7de97995f9a5e0f857bef"
uuid = "0e394dc1-71ae-5c65-abe5-8749687e42d3"
version = "1.5.0+0"

[[Xorg_recordproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "0192d9bc3f2bfdd90191e055c412c3fd3faf4b1d"
uuid = "a7b44dc7-5846-51fe-a1cd-6b242f0ec0a2"
version = "1.14.2+0"

[[Xorg_renderproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ce13e67a75e2e6338500f22af11003823bf189b5"
uuid = "21e99dc2-7dba-5609-a726-b181bd3bbb6c"
version = "0.11.1+1"

[[Xorg_util_macros_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "50c9763d05bdc0795a19877bae9274ada3e499d1"
uuid = "7c09cfe3-afe2-5798-bcc9-d6b7fecfdca5"
version = "1.19.2+1"

[[Xorg_xcb_proto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "c0817a62c2a53dd97469f1934e32461cedaf400d"
uuid = "c2e9c405-c068-5e7b-9b35-084fd074cae4"
version = "1.13.0+1"

[[Xorg_xextproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "49ac1f9b3f5b775141690a64b40f401527996a76"
uuid = "d13bc2ba-d276-5c6f-8a1c-29ed04aab5d0"
version = "7.3.0+1"

[[Xorg_xineramaproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9f331b569a18a4fbf66ee8f60cb4018c73faabb4"
uuid = "6a3da44c-33b1-5374-838f-bf0fbf92c29b"
version = "1.2.1+0"

[[Xorg_xkbcomp_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxkbfile_jll", "Xorg_util_macros_jll"]
git-tree-sha1 = "5100f4a2210097636ae070505a3aa2d086cb88d4"
uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4"
version = "1.4.2+1"

[[Xorg_xkeyboard_config_jll]]
deps = ["Libdl", "Pkg", "Xorg_xkbcomp_jll"]
git-tree-sha1 = "416f9257ada9365f53766394af77134bf594e1a2"
uuid = "33bec58e-1273-512f-9401-5d533626f822"
version = "2.27.0+1"

[[Xorg_xproto_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "1528b6cef487b060c47bb5894824f30143489023"
uuid = "46797783-dccc-5433-be59-056c4bde8513"
version = "7.0.31+1"

[[Xorg_xtrans_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b6e7d70f5fc9e3fde505539194c8caaab3c40ebf"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+1"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2f6c3e15e20e036ee0a0965879b31442b7ec50fa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+9"

[[Zstd_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "aa97e3e240e86010da61254b0045b7175ead0659"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.4+0"

[[adwaita_icon_theme_jll]]
deps = ["Libdl", "Pkg", "hicolor_icon_theme_jll"]
git-tree-sha1 = "245d4d5884e54d171c9683e1d30213358ddeb648"
uuid = "b437f822-2cd6-5e08-a15c-8bac984d38ee"
version = "3.33.92+3"

[[at_spi2_atk_jll]]
deps = ["ATK_jll", "Libdl", "Pkg", "XML2_jll", "Xorg_libX11_jll", "at_spi2_core_jll"]
git-tree-sha1 = "c896019bced4ebbf7e507e66fa403ec4409a1937"
uuid = "de012916-1e3f-58c2-8f29-df3ef51d412d"
version = "2.34.1+0"

[[at_spi2_core_jll]]
deps = ["Dbus_jll", "Glib_jll", "Libdl", "Pkg", "Xorg_libXtst_jll"]
git-tree-sha1 = "db3118da77a00c375c04ff3df08daa4045324b44"
uuid = "0fc3237b-ac94-5853-b45c-d43d59a06200"
version = "2.34.0+0"

[[gdk_pixbuf_jll]]
deps = ["Glib_jll", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg", "X11_jll", "Xorg_libX11_jll", "libpng_jll"]
git-tree-sha1 = "566ebf4b2c9efd81b35eb914c325026831077f39"
uuid = "da03df04-f53b-5353-a52f-6a8b0620ced0"
version = "2.38.2+6"

[[hicolor_icon_theme_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4f8addaf9ca8492b0ba3f289587c983ba395dd60"
uuid = "059c91fe-1bad-52ad-bddd-f7b78713c282"
version = "0.17.0+1"

[[iso_codes_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "46515ba7486a978a3f6418ce060a3407ed837e1e"
uuid = "bf975903-5238-5d20-8243-bc370bc1e7e5"
version = "4.3.0+1"

[[libpng_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "594cb058723c13941cf463fd09e5859499594f50"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+3"

[[xkbcommon_jll]]
deps = ["Libdl", "Pkg", "Wayland_jll", "Wayland_protocols_jll", "Xorg_libxcb_jll", "Xorg_xkeyboard_config_jll"]
git-tree-sha1 = "cbed604f26643b998f29b74b2a2f73298cb07606"
uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
version = "0.9.1+1"
